name: Update Trophies
on:
  schedule:
    - cron: "0 0 * * *" # Runs every night
  workflow_dispatch:   # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dr-developer1
          theme: tokyonight
          # Add other parameters here if needed
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update trophies" || exit 0
          git push
