name: Update Trophies
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true # Ensures we can push back to the repo

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dr-developer1
          theme: tokyonight

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git commit -m "Update trophies" || echo "No changes to commit"
          git push origin main
